# Generated by Django 3.0.1 on 2021-01-19 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('COVID_19_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
