# Generated by Django 3.0.1 on 2021-01-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID_19_Tracker', '0002_global_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
