# Generated by Django 3.0.1 on 2021-01-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID_19_Tracker', '0003_auto_20210119_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='slugId',
            field=models.SlugField(),
        ),
    ]
