# Generated by Django 3.0.1 on 2021-01-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID_19_Tracker', '0004_auto_20210120_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=10000, unique=True)),
                ('country', models.CharField(max_length=1000)),
                ('countryCode', models.CharField(max_length=100)),
                ('slugId', models.SlugField()),
                ('newConfirmed', models.IntegerField()),
                ('totalConfirmed', models.IntegerField()),
                ('newDeaths', models.IntegerField()),
                ('totalDeaths', models.IntegerField()),
                ('newRecovered', models.IntegerField()),
                ('totalRecoverd', models.BigIntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
