# Generated by Django 3.0.1 on 2021-01-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('COVID_19_Tracker', '0005_countrieshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrieshistory',
            name='saved_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
