# Generated by Django 3.0.1 on 2021-01-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID_19_Tracker', '0008_auto_20210121_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='india',
            name='last_update_time',
            field=models.DateTimeField(),
        ),
    ]
