# Generated by Django 3.0.1 on 2021-01-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID_19_Tracker', '0009_auto_20210121_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='india',
            name='state_code',
            field=models.CharField(max_length=100),
        ),
    ]
