# Generated by Django 3.0.1 on 2021-01-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('COVID_19_Tracker', '0011_global_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiaHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1000)),
                ('state_code', models.CharField(max_length=100)),
                ('active', models.BigIntegerField()),
                ('confirmed', models.BigIntegerField()),
                ('deaths', models.BigIntegerField()),
                ('recovered', models.BigIntegerField()),
                ('new_confirmed', models.BigIntegerField()),
                ('new_deaths', models.BigIntegerField()),
                ('new_recovered', models.BigIntegerField()),
                ('last_update_time', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
