# Generated by Django 3.0.1 on 2021-01-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID_19_Tracker', '0012_indiahistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='gid',
            field=models.CharField(max_length=100000),
        ),
    ]
