# Generated by Django 3.0.1 on 2021-01-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID_19_Tracker', '0014_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=10000, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=10000, null=True),
        ),
    ]
