# Generated by Django 3.0.1 on 2021-01-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID_19_Tracker', '0016_auto_20210131_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global',
            name='gid',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
