# Generated by Django 3.0.1 on 2021-02-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COVID_19_Tracker', '0018_auto_20210201_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=60, null=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=60, null=True),
        ),
    ]
