# Generated by Django 3.0.1 on 2021-02-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('COVID_19_Tracker', '0017_auto_20210131_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='countries',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
